[package]
name = "datafusion-bio-format-bam"
version = "0.1.1"
description = "BAM file format support for Apache DataFusion"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
async-stream.workspace = true
async-trait.workspace = true
datafusion.workspace = true
opendal.workspace = true
log = "0.4.27"
tokio-util.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
bytes.workspace = true
datafusion-bio-format-core = {path = "../bio-format-core"}
futures.workspace = true
futures-util.workspace = true
noodles-bgzf.workspace = true
noodles = { version = "0.93.0",  features = ["sam", "bam", "async"]}
oxbow.workspace = true

[[example]]
name = "test_bam_reader"
path = "./examples/test_bam_reader.rs"
